# Generated by Django 4.2.30 on 2026-07-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('WHATSAPP', 'WhatsApp'), ('KIOSK', 'Kiosk'), ('API', 'External API')], default='WEB', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('READY_FOR_AI', 'Ready for AI'), ('AI_PROCESSING', 'AI Processing'), ('ANALYZED', 'Analyzed'), ('GROUPED', 'Grouped'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('storage_provider', models.CharField(default='CLOUDINARY', max_length=50)),
                ('public_id', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=50)),
                ('secure_url', models.URLField(max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='problems.problem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', 'created_at'], name='problems_pr_status_219cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['district', 'ward'], name='problems_pr_distric_7acc99_idx'),
        ),
    ]
