# Generated by Django 5.2.15 on 2026-07-05 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('priority_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True)),
                ('priority_reasoning', models.TextField(blank=True)),
                ('estimated_affected_population', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('PRIORITIZED', 'Prioritized'), ('PROPOSAL_READY', 'Proposal Ready'), ('PENDING_MP_REVIEW', 'Pending MP Review'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CHANGES', 'Approved With Changes')], db_index=True, default='IDENTIFIED', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='intelligence.issue')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='problems.problem')),
            ],
            options={
                'ordering': ['linked_at'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='problems',
            field=models.ManyToManyField(related_name='issues', through='intelligence.IssueProblem', to='problems.problem'),
        ),
        migrations.AddConstraint(
            model_name='issueproblem',
            constraint=models.UniqueConstraint(fields=('issue', 'problem'), name='unique_issue_problem'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'priority_score'], name='intelligenc_status_04d440_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category', 'district', 'ward'], name='intelligenc_categor_963041_idx'),
        ),
    ]
