# Generated by Django 5.2.15 on 2026-07-05 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_solution', models.TextField()),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget_reasoning', models.TextField(blank=True)),
                ('implementation_plan', models.TextField(blank=True)),
                ('expected_impact', models.TextField(blank=True)),
                ('estimated_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('final_solution', models.TextField(blank=True)),
                ('final_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mp_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI Draft'), ('PENDING_MP_REVIEW', 'Pending MP Review'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CHANGES', 'Approved With Changes')], db_index=True, default='AI_DRAFT', max_length=40)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='intelligence.issue')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue__priority_score', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='intelligenc_status_1915ba_idx')],
            },
        ),
    ]
